1. fixed code generation for argv[]. 2. add printPrettyPrint() method for debugging.
[argv.cpp => argv.ll]
int main(int argc, char **argv)
{
    if(1 == argc) {
        printf("argc = 1\n");
    }
    else if(1 < argc) {
        printf("argv[1] = %s\n", argv[1]);
    }
    return 0;
}

Error occurs on `llvm-cbe argv.ll` command:

/tmp/llvm-cbe-test-11340/output.cbe.c: In function ‘main’:
/tmp/llvm-cbe-test-11340/output.cbe.c:181:68: error: expected ‘;’ before ‘)’ token
   llvm_cbe_tmp__10 = *((&llvm_cbe_tmp__9)+(((int64_t)UINT64_C(1))))));
                                                                    ^
/tmp/llvm-cbe-test-11340/output.cbe.c:181:68: error: expected statement before ‘)’ token
/tmp/llvm-cbe-test-11340/output.cbe.c:181:69: error: expected statement before ‘)’ token
   llvm_cbe_tmp__10 = *((&llvm_cbe_tmp__9)+(((int64_t)UINT64_C(1))))));
                                                                     ^
The resulting program isn't compilable
> 1:  /* Provide Declarations */

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -30,6 +30,8 @@ function main
   runTest execute_test    flexible_arrays.ll
   runTest execute_c_test  helloworld.cpp
   runTest execute_c_test  helloworld2.cpp
+  runTest execute_c_test  argv.cpp
+  runTest execute_c_test  argv.cpp  arg1
 }
 
 function runTest
@@ -96,9 +98,17 @@ function execute_c_test
     return 1
   fi
 
-  if ! $tmpDir/output.exe ; then
-    echo "The resulting program returns an error" >&2
-    return 1
+  if [ $# -eq 1 ] ; then
+    if ! $tmpDir/output.exe  ; then
+      echo "The resulting program returns an error" >&2
+      return 1
+    fi
+  fi
+  if [ $# -eq 2 ] ; then
+    if ! $tmpDir/output.exe $2; then
+      echo "The resulting program returns an error" >&2
+      return 1
+    fi
   fi
 }
 
